[colors]

[colors.bright]
black = "#808080"
blue = "#0066ff"
cyan = "#00ffff"
green = "#33ff00"
magenta = "#cc00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ff0099"

[colors.cursor]
cursor = "#d0d0d0"
text = "#000000"

[colors.normal]
black = "#000000"
blue = "#0066ff"
cyan = "#00ffff"
green = "#33ff00"
magenta = "#cc00ff"
red = "#ff0000"
white = "#d0d0d0"
yellow = "#ff0099"

[colors.primary]
background = "#000000"
foreground = "#d0d0d0"

[window]
opacity = 0.75
